metadata:
  resourceType: APPLICATION
  name: test application with yml
  description: application created by yml
spec:
  githubUrl: ''
  applicationType: REDIS
  port: 3306
  version: latest
  labels:
    - test-with-yml